# GitHub PR Auto-Labeler Configuration
# Format for actions/labeler@v5

terraform:
  - changed-files:
    - any-glob-to-any-file: 'terraform/**/*'
  - changed-files:
    - any-glob-to-any-file: '**/*.tf'

ansible:
  - changed-files:
    - any-glob-to-any-file: 'ansible/**/*'
  - changed-files:
    - any-glob-to-any-file: '**/*.yml'
  - changed-files:
    - any-glob-to-any-file: '**/*.yaml'

documentation:
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
  - changed-files:
    - any-glob-to-any-file: 'README.md'

ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'
  - changed-files:
    - any-glob-to-any-file: '.pre-commit-config.yaml'

scripts:
  - changed-files:
    - any-glob-to-any-file: 'scripts/**/*'
  - changed-files:
    - any-glob-to-any-file: '**/*.sh'

security:
  - changed-files:
    - any-glob-to-any-file: '.secrets.baseline'
  - changed-files:
    - any-glob-to-any-file: '.tflint.hcl'
  - changed-files:
    - any-glob-to-any-file: '.yamllint'

dependencies:
  - changed-files:
    - any-glob-to-any-file: '**/requirements.txt'
  - changed-files:
    - any-glob-to-any-file: '**/requirements.yml'
  - changed-files:
    - any-glob-to-any-file: 'package.json'
  - changed-files:
    - any-glob-to-any-file: 'go.mod'
  - changed-files:
    - any-glob-to-any-file: 'Gemfile'
